---

- git:
    repo: https://github.com/rackerlabs/recap.git
    dest: /home/rack/recap

- make:
    chdir: /home/rack/recap
    target: install

- template:
    src: /home/rack/preqc/templates/recap.j2
    dest: /etc/cron.d/recap

